import React, { useCallback, useEffect, useState } from 'react';
import { Radar, Route, PackageSearch, Zap, RefreshCw, AlertOctagon, ArrowRight, Users, Timer, Gauge, CheckCircle2, Activity, Sparkles, LoaderCircle } from 'lucide-react';
import * as api from '../lib/api';
import PageHeader from './PageHeader';

const RISK={missed:['Cutoff missed','bg-red-50 text-red-700 border-red-200','bg-red-500'],will_miss:['Will miss cutoff','bg-red-50 text-red-700 border-red-200','bg-red-500'],at_risk:['At risk','bg-amber-50 text-amber-800 border-amber-200','bg-amber-500'],on_track:['On track','bg-emerald-50 text-emerald-700 border-emerald-200','bg-emerald-500'],clear:['Nothing pending','bg-slate-50 text-slate-600 border-slate-200','bg-slate-300']};
const LEVEL={critical:['Critical','bg-red-50 text-red-700 border-red-200'],act_now:['Act now','bg-amber-50 text-amber-800 border-amber-200'],watch:['Watch','bg-blue-50 text-blue-700 border-blue-200'],ok:['Healthy','bg-emerald-50 text-emerald-700 border-emerald-200']};
const fmtMin=m=>(m<0?`${Math.abs(m)} min ago`:m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m} min`);
const Card=({icon:Icon,title,hint,right,children})=><section className="ops-card command-card p-5"><div className="flex items-start justify-between gap-4 mb-4"><div className="flex items-start gap-3"><div className="w-9 h-9 rounded-xl bg-slate-100 flex items-center justify-center shrink-0"><Icon className="w-[18px] h-[18px] text-slate-700"/></div><div><h2 className="text-base font-extrabold">{title}</h2>{hint&&<p className="text-xs text-slate-500 mt-0.5 max-w-xl">{hint}</p>}</div></div>{right}</div>{children}</section>;
const Slider=({icon:Icon,label,value,min,max,step=1,onChange,unit=''})=><label className="command-planning-control">
  <span className="command-planning-control-heading"><span className="command-planning-control-label"><Icon aria-hidden="true"/>{label}</span><span className="command-planning-value">{value}{unit}</span></span>
  <input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} className="command-planning-range"/>
  <span className="command-planning-scale"><span>{min}{unit}</span><span>{max}{unit}</span></span>
</label>;

export default function CommandCenter({onNavigate,workers=[],activity=[]}){
  const [team,setTeam]=useState(Math.max(1,workers.filter(w=>w.role==='Packer'&&w.presentToday).length||3));
  const [mpo,setMpo]=useState(3);
  const [data,setData]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const [workerLogs,setWorkerLogs]=useState([]); const [selectedWorker,setSelectedWorker]=useState('');
  const [productivityAdvice,setProductivityAdvice]=useState(null); const [adviceLoading,setAdviceLoading]=useState(false); const [adviceError,setAdviceError]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{setData(await api.getInsights({team,minutesPerOrder:mpo,waveSize:12}));setError('')}catch(e){setError(api.errorMessage(e,'Could not load insights'))}finally{setLoading(false)}},[team,mpo]);
  const loadWorkers=useCallback(async()=>{try{const rows=await api.getWorkerLogs();setWorkerLogs(rows);setSelectedWorker(prev=>prev||rows[0]?.id||'')}catch(e){setError(api.errorMessage(e,'Could not load worker logs'))}},[]);
  useEffect(()=>{load();loadWorkers();const t=setInterval(()=>{load();loadWorkers()},30000);return()=>clearInterval(t)},[load,loadWorkers]);
  const selected=workerLogs.find(w=>w.id===selectedWorker)||workerLogs[0];
  const mine=selected?.recentActivity||[];
  const loadProductivityAdvice=async()=>{setAdviceLoading(true);setAdviceError('');try{const result=await api.getOverdueSuggestions({team,minutesPerOrder:mpo});setProductivityAdvice(result)}catch(e){setAdviceError(api.errorMessage(e,'Could not prepare productivity guidance. Try again.'))}finally{setAdviceLoading(false)}};
  if(!data)return <div className="p-6"><div className="ops-card p-10 text-center text-slate-500">{error?<><p className="font-semibold text-red-600 mb-3">{error}</p><button onClick={load} className="px-4 py-2 rounded-lg bg-slate-950 text-white text-sm font-semibold cursor-pointer">Retry</button></>:'Analysing operations…'}</div></div>;
  const {kpis,radar,wave,forecast,actions}=data;
  const kpiCards=[['Priority at risk',kpis.priorityAtRisk,'overdue or due in 60 min',kpis.priorityAtRisk?'text-red-600':'text-slate-900',Zap],['Stock actions',kpis.stockActions,'SKUs short vs open demand',kpis.stockActions?'text-amber-600':'text-slate-900',PackageSearch],['Pick-wave saving',`${kpis.waveSavingPct}%`,`${kpis.waveStopsSaved} fewer shelf stops`,'text-emerald-600',Route],['Mis-scans caught',kpis.misScans,'wrong items stopped today','text-slate-900',Gauge]];
  return <div className="ops-page space-y-5">
    <PageHeader title="Command Center" right={<button onClick={()=>{load();loadWorkers()}} title="Refresh now" aria-label="Refresh command center" className="command-refresh-button"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button>}/>
    <div className="command-top-grid">
      <section className="command-team-planning ops-card command-card p-5" aria-label="Team and planning assumptions">
        <div className="command-planning-heading"><div><h2>Team & planning</h2><p>Set shift capacity and check today’s team.</p></div><span>LIVE SCENARIO</span></div>
        <div className="command-planning-controls"><Slider icon={Users} label="Packers available" value={team} min={1} max={10} onChange={setTeam}/><Slider icon={Timer} label="Minutes per order" value={mpo} min={1} max={10} step={0.5} onChange={setMpo} unit="m"/></div>
        <div className="command-productivity" aria-label="Estimated work efficiency">
          <div><span>Estimated team capacity</span><strong>{Math.round(team * 60 / mpo)} <small>orders / hour</small></strong></div>
          <div><span>Open queue at this pace</span><strong>{(kpis.openOrders * mpo / (team * 60)).toFixed(1)} <small>team hours</small></strong></div>
          <p>Planning estimate from your slider settings, not a measured performance score.</p>
        </div>
      </section>
      <div className="command-summary-column">
        <div className="dashboard-kpi-grid command-kpi-grid grid grid-cols-2 gap-3">{kpiCards.map(([label,value,sub,cls,Icon])=><div key={label} className="ops-card dashboard-kpi-card p-4"><div className="flex items-center justify-between"><span className="metric-label">{label}</span><Icon className="w-4 h-4 text-slate-400"/></div><div className={`metric-value text-[26px] mt-2 ${cls}`}>{value}</div><div className="text-[10px] text-slate-500 mt-1">{sub}</div></div>)}</div>
      </div>
    </div>
    <section className="ops-card command-card p-5" aria-label="Workers today">
      <div className="command-team-heading"><div><h2 className="text-sm font-extrabold">Workers today</h2><p className="text-xs text-slate-500 mt-0.5">Shift attendance and last activity</p></div><span>{(workerLogs.length?workerLogs:workers).filter(w=>w.presentToday).length} present</span></div>
      <div className="command-worker-list">{(workerLogs.length?workerLogs:workers).map(w=><button key={w.id} onClick={()=>setSelectedWorker(w.id)} className={`command-worker-item ${selectedWorker===w.id?'is-selected':''}`}><span className="command-worker-name">{w.name}</span><span className="command-worker-meta">{w.role} · {w.shift}</span><span className={`command-worker-status ${w.presentToday?'is-present':'is-off'}`}>{w.presentToday?'Present':'Off'}</span><span className="command-worker-last">Last active {w.lastActiveAt?new Date(w.lastActiveAt).toLocaleString():'—'}</span></button>)}</div>
      {!workerLogs.length&&!workers.length&&<p className="mt-3 text-xs text-slate-500">Worker roster is not available yet.</p>}
    </section>
    <div className="command-operations-grid">
      <Card icon={AlertOctagon} title="Next best actions" hint="Prioritized actions from live operational signals." right={<button type="button" onClick={loadProductivityAdvice} disabled={adviceLoading} className="ops-secondary inline-flex items-center gap-2 px-3 py-2 text-xs disabled:opacity-60" aria-busy={adviceLoading}>{adviceLoading?<LoaderCircle className="w-3.5 h-3.5 animate-spin"/>:<Sparkles className="w-3.5 h-3.5"/>}{adviceLoading?'Analyzing…':productivityAdvice?'Refresh guidance':'Improve productivity'}</button>}>
        {actions.length===0?<p className="text-sm text-emerald-700 bg-emerald-50 border border-emerald-200 rounded-xl p-4">No urgent action detected.</p>:<ul className="space-y-2">{actions.map((a,i)=><li key={i}><button onClick={()=>onNavigate(a.target)} className="w-full text-left flex items-center gap-4 border border-slate-200 hover:border-blue-400 rounded-xl px-4 py-3 cursor-pointer"><span className={`text-[10px] font-bold uppercase px-2.5 py-1 rounded-full border shrink-0 ${a.severity==='critical'?'bg-red-50 text-red-700 border-red-200':'bg-amber-50 text-amber-800 border-amber-200'}`}>{a.severity}</span><span className="text-sm text-slate-800 flex-1">{a.title}</span><ArrowRight className="w-4 h-4 text-slate-400"/></button></li>)}</ul>}
        {adviceError&&<p role="alert" className="mt-3 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-xs text-rose-700">{adviceError}</p>}
        {productivityAdvice&&<section className="mt-4 rounded-xl border border-blue-100 bg-blue-50/50 p-4" aria-label="Productivity guidance">
          <div className="mb-3 flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs font-bold text-slate-800"><Sparkles className="h-4 w-4 text-blue-600"/>Productivity guidance <span className="rounded-full border border-blue-200 bg-white px-2 py-0.5 text-[9px] font-semibold text-blue-700">LIVE DATA</span></div><span className="text-[10px] text-slate-500">Team {team} · {mpo} min/order</span></div>
          <ol className="grid gap-2">{productivityAdvice.suggestions.map((suggestion,index)=><li key={`${index}-${suggestion}`}><button type="button" onClick={()=>onNavigate(['orders','orders','worker','inventory'][index]||'orders')} className="group flex w-full items-start gap-3 rounded-lg border border-blue-100 bg-white px-3 py-2.5 text-left transition hover:border-blue-300 hover:shadow-sm"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-blue-50 text-[10px] font-extrabold text-blue-700">{index+1}</span><span className="flex-1 text-xs leading-relaxed text-slate-700">{suggestion}</span><ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-400 transition group-hover:translate-x-0.5 group-hover:text-blue-600"/></button></li>)}</ol>
          <p className="mt-3 text-[10px] text-slate-500">Recommendations use current queue, courier, stock and pick-wave data. Adjust the planning controls above, then refresh guidance to recalculate.</p>
        </section>}
      </Card>
      <Card icon={Radar} title="Cutoff Radar" hint="Orders to pack and time remaining for each courier."><div className="command-radar-list">{radar.map(r=>{const [label,pill,bar]=RISK[r.risk];const total=r.notReady+r.staged||1;return <div key={r.courier} className="command-radar-item"><div className="flex items-center justify-between gap-2"><span className="font-bold">{r.courier}</span><span className={`text-[10px] font-bold px-2.5 py-1 rounded-full border ${pill}`}>{label}</span></div><div className="text-xs text-slate-500 mt-1">Cutoff {r.cutoff} · pickup {r.pickup}</div><div className="mt-3 flex items-end justify-between"><div><div className="text-2xl font-extrabold">{r.minutesLeft<0?'—':fmtMin(r.minutesLeft)}</div><div className="text-[11px] text-slate-500">{r.minutesLeft<0?`passed ${fmtMin(r.minutesLeft)}`:'until cutoff'}</div></div><div className="text-right"><div className="text-2xl font-extrabold">{r.notReady}</div><div className="text-[11px] text-slate-500">to pack</div></div></div><div className="mt-3 h-2 rounded-full bg-slate-100 overflow-hidden"><div className={`h-full ${bar}`} style={{width:`${Math.round((r.staged/total)*100)}%`}}/></div><div className="mt-2 text-[11px] text-slate-500 flex justify-between"><span>{r.staged} staged</span><span>{r.notReady?`~${r.workMinutes} min work`:''}{r.priorityNotReady?` · ${r.priorityNotReady} priority`:''}</span></div></div>})}</div></Card>
    </div>
    <Card icon={Activity} title="Worker-wise saved logs" hint="Admin view of each worker's persistent operational activity. Select a worker to inspect their timeline." right={selected&&<div className="flex items-center gap-2"><select aria-label="Select worker for activity log" value={selected.id} onChange={e=>setSelectedWorker(e.target.value)} className="ops-field w-56">{workerLogs.map(w=><option key={w.id} value={w.id}>{w.name} · {w.role}</option>)}</select><button onClick={loadWorkers} className="ops-secondary px-3" title="Refresh worker logs"><RefreshCw className="w-4 h-4"/></button></div>}>
      {selected?<><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-4">{[['Units picked',selected.stats?.unitsPicked||0],['Mis-scans',selected.stats?.misScans||0],['Boxes sealed',selected.stats?.boxesSealed||0],['Orders handled',selected.stats?.ordersHandled||0]].map(([l,v])=><div key={l} className="ops-panel"><div className="metric-label">{l}</div><div className="text-xl font-extrabold mt-1">{v}</div></div>)}</div><div className="space-y-1 max-h-[360px] overflow-y-auto pr-1">{mine.map(a=><div key={a.id} className="border border-slate-100 rounded-lg px-3 py-2.5 flex items-center gap-3"><div className={`w-7 h-7 rounded-lg flex items-center justify-center ${a.type==='scan_error'?'bg-red-50 text-red-600':'bg-emerald-50 text-emerald-600'}`}>{a.type==='scan_error'?<AlertOctagon className="w-3.5 h-3.5"/>:<CheckCircle2 className="w-3.5 h-3.5"/>}</div><div className="flex-1 min-w-0"><div className="text-xs font-semibold truncate">{a.message}</div><div className="text-[10px] text-slate-400">{a.orderId||'Operations'} · {new Date(a.timestamp).toLocaleString()}</div></div></div>)}{!mine.length&&<div className="p-8 text-center text-xs text-slate-400">No saved activity for this worker.</div>}</div></>:<div className="p-8 text-center text-xs text-slate-400">Worker logs are unavailable.</div>}
    </Card>
    <Card icon={Route} title="Smart pick wave" hint={`Next ${wave.orders.length} orders, priority first, merged into one aisle-ordered route.`} right={<button onClick={()=>onNavigate('worker')} className="ops-primary">Start picking</button>}>{wave.route.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-[11px] uppercase tracking-wider text-slate-500">{['Stop','Location','Item','Pick qty','Orders','Stock'].map(h=><th key={h} className="pb-3 pr-4 font-semibold">{h}</th>)}</tr></thead><tbody>{wave.route.map((s,i)=><tr key={s.sku} className="border-t border-slate-100"><td className="py-3 pr-4 font-mono font-bold text-slate-400">{i+1}</td><td className="py-3 pr-4">{s.location}</td><td className="py-3 pr-4"><div className="font-semibold">{s.product}</div><div className="text-xs text-slate-500">{s.variant} · <span className="font-mono">{s.sku}</span></div></td><td className="py-3 pr-4 font-mono text-lg font-bold">{s.qty}</td><td className="py-3 pr-4 text-xs text-slate-500 font-mono">{s.orders.join(', ')}</td><td className="py-3">{s.shortBy>0?<span className="text-xs font-bold text-red-700 bg-red-50 border border-red-200 px-2.5 py-1 rounded-full">short by {s.shortBy}</span>:<span className="text-xs font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 px-2.5 py-1 rounded-full">{s.mainStock} on shelf</span>}</td></tr>)}</tbody></table></div>:<p className="text-sm text-slate-500">No pick wave available.</p>}</Card>
    <Card icon={PackageSearch} title="Stock shortfall forecast" hint="Main-shelf coverage versus open demand and inbound stock." right={<button onClick={()=>onNavigate('inventory')} className="ops-secondary">Open stock</button>}><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-[11px] uppercase tracking-wider text-slate-500">{['Product','Shelf','WH2','Open demand','Inbound','Status','Recommended action'].map(h=><th key={h} className="pb-3 pr-4 font-semibold">{h}</th>)}</tr></thead><tbody>{forecast.map(f=><tr key={f.sku} className="border-t border-slate-100"><td className="py-3 pr-4"><div className="font-semibold">{f.product}</div><div className="text-xs text-slate-500">{f.variant}</div></td><td className="py-3 pr-4 font-mono font-bold">{f.mainQty}</td><td className="py-3 pr-4 font-mono text-slate-500">{f.wh2Qty}</td><td className="py-3 pr-4 font-mono">{f.openDemand}</td><td className="py-3 pr-4 font-mono text-slate-500">{f.inbound||'—'}</td><td className="py-3 pr-4"><span className={`text-[10px] font-bold uppercase px-2.5 py-1 rounded-full border ${LEVEL[f.level][1]}`}>{LEVEL[f.level][0]}</span></td><td className="py-3 text-slate-700">{f.action}</td></tr>)}</tbody></table></div></Card>
  </div>;
}
